### ISSUE TITLE
After effects integration in the DCCs tab not present

### ISSUE THREAD

**Issue by Byter3** [kapellan2000/AfterEffects#3]
I know it sais " prism v2.0.0.beta14.1", so close it if no plan to update it, to the current version of Prism.

But after extracting the Contents into the Prism plug-ins folder and restarting the entire computer, the After effects integration in the DCCs tab still not present.

**Comment by kapellan2000** [comment]
Are you sure you placed the plugin in ProgramData?

and after that they added the path to it?
![Screenshot 2024-04-11 082358](https://github.com/kapellan2000/AfterEffects/assets/21256398/7ebd4ae6-1447-416d-aa96-41992242b33e)

**Comment by Byter3** [comment]
Solved it thank you
